# Generated by Django 6.0.5 on 2026-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_favorite_menuitem_openinghours_profile_reviewreply_and_more'),
    ]

    def verify_existing_restaurants(apps, schema_editor):
        Restaurant = apps.get_model('myapp', 'Restaurant')
        Restaurant.objects.update(is_verified=True)

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Only verified restaurants are visible to the public. Admin/staff submissions are auto-verified.'),
        ),
        migrations.RunPython(verify_existing_restaurants, migrations.RunPython.noop),
    ]
